### ISSUE TITLE
Loading bar

### ISSUE THREAD

**Issue by NVHT** [witalihirsch/qBitTorrent-fluent-theme#41]
![image](https://user-images.githubusercontent.com/8341213/219345772-0b31e286-85e9-4c35-a096-b8fe4176b689.png)

Can you remove the black bar and subtle background for the loading area.

**Comment by emwedk** [comment]
i simply can't force that progressbar, no matter the size of file i try to open 
\- dunno if it's because of my ultra fast NVMe or if it's the source.

however i might have found the "issue" - atleast it didn't brake any other progressbar and had represented something very alike

try to download the theme that match yours from https://github.com/emwedk/qBitTorrent-fluent-theme
the vanillaIcons, is if you don't use white icons and rather wanna use qbits original icons

**Comment by NVHT** [comment]
![image](https://user-images.githubusercontent.com/8341213/219605108-a30d86df-9321-4997-8740-576c7317455c.png)

Look goods now. Thanks.
