### ISSUE TITLE
Download progress bar has its corners rounded only after 11%

### ISSUE THREAD

**Issue by XKillSwitchXxx** [witalihirsch/qBitTorrent-fluent-theme#7]
**The bar has rounded corners at 0%** but as downloading starts **it's a plain rectangle until 10.9%** 
After which, starting **from 11% it behaves as intended**

![10](https://user-images.githubusercontent.com/93640338/173228360-98dbde34-89ce-4937-ba10-b1599ebe1f83.png)
![11](https://user-images.githubusercontent.com/93640338/173228362-36b314f7-a7e8-4f81-93c2-67ab97e4f556.png)

**Comment by witalihirsch** [comment]
I'd to narrow the size of the qprogressbar and reduce the border-radius and now the chunk is loading by about 4%. The problem isn't solved, but that's all I've been able to do so far. This is due to the fact that while the load area is too small, the property for rounding cannot be applied, so it seems to me that qss cannot fix this, but only slightly reduce it.
![image](https://user-images.githubusercontent.com/73841541/173235305-4d2ade9f-a5c8-422d-8710-62eb6f6420e2.png)

**Comment by XKillSwitchXxx** [comment]
Understandable! 
Can we make it apply in such a way that, the rounded corners are applied on the left end, but not on the right end, right away, but after a suitable threshold as the download progresses?
Right now, as per v2.2, the size of the qprogressbar is a barely housing the percentage imo, if the numbers are claustrophobic, I feel bad for them :(

Thanks

**Comment by witalihirsch** [comment]
What do you think about this? I think it looks pretty similar to WinUI 3
![image](https://user-images.githubusercontent.com/73841541/173387283-58105e6f-e7a3-4f74-afac-9c1588f4040d.png)
