### ISSUE TITLE
Request - Context menu rounded corners

### ISSUE THREAD

**Issue by dr-baba** [witalihirsch/qBitTorrent-fluent-theme#9]
I think it would look nice if the context menus had rounded corners to match Windows 11 menus.

**Comment by witalihirsch** [comment]
because of the shadows, it looks weird, and you can’t remove them using qss, as far as I know
![Снимок экрана 2022-06-16 183749](https://user-images.githubusercontent.com/73841541/174062242-c329269f-072f-464a-9d47-537fcbeea499.png)
![Снимок экрана 2022-06-16 184034](https://user-images.githubusercontent.com/73841541/174062247-8cc2f430-d090-4a57-a3a3-c532e51ec9c0.png)
